apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    env: dev
    tier: db
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      tier: db
      project: roboshop

  template:
    metadata:
      labels:
        env: dev
        tier: db
        project: roboshop

    spec:
      containers:
      - name: payment
        image: surajk879/payment:1.9
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment

---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop

spec:
  selector:
    tier: db
    env: dev
    project: roboshop

  ports:
  - name: payment
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"




