apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    env: dev
    tier: db
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      tier: db
      project: roboshop

  template:
    metadata:
      labels:
        env: dev
        tier: db
        project: roboshop

    spec:
      containers:
      - name: cart
        image: surajk879/cart:1.9
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart

---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop

spec:
  selector:
    tier: db
    env: dev
    project: roboshop

  ports:
  - name: cart
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  


