apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    env: dev
    tier: db
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      tier: db
      project: roboshop

  template:
    metadata:
      labels:
        env: dev
        tier: db
        project: roboshop

    spec:
      containers:
      - name: shipping
        image: surajk879/shipping:1.9
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping

---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop

spec:
  selector:
    tier: db
    env: dev
    project: roboshop

  ports:
  - name: shipping
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
  


